### ISSUE TITLE
BIGBOOT option specified wrong in makeall

### ISSUE THREAD

**Issue by WestfW** [MCUdude/optiboot_flash#2]
makeall has lines like:

```
"atmega64"    "LED=B5 LED_START_FLASHES=2 UART=0 -BIGBOOT"
"atmega64" "LED=B5 LED_START_FLASHES=2 UART=1 -BIGBOOT"
```
Except I don't think that that use of "-BIGBOOT" does the right thing (or anything, really.)
It should be

```
"atmega64"    "LED=B5 LED_START_FLASHES=2 UART=0 BIGBOOT=1"
"atmega64" "LED=B5 LED_START_FLASHES=2 UART=1 BIGBOOT=1"
```

(However, I don't think this matters anywhere, since Makefile defines BIGBOOT as needed for the processors that actually require it.   It would only become an issue if you were trying to build a BIGBOOT version of something like a m328...)

PS: I really like the shell-script based build of all the variants.  I added a bunch of the Attiny targets via the makefiles recently, and it was ... annoying.

**Comment by MCUdude** [comment]
Thanks for he heads up! I actually forked Optiboot 7.0 last week and actually fixed this (but haven't pushed it yet).

I've removed the BIGBOOT flag found in the makefile in he new version (I've called it optiboot_flash 7.1 if you don't mind). This way EEPROM_SUPPORT/BIGBOOT can be toggled in the makeall file instead.

Yes, I ended up spending a few evenings on a build script rather than continoulsy adding more build options to the old file (which was almost 2000 lines long).
